version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    container_name: totem-container
    networks:
      totem-network:
        ipv4_address: 192.168.10.1

networks:
  totem-network:
    name: totem-network
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/30"
