version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    container_name: totem-container
    networks:
      app-network:
        ipv4_address: 172.16.238.2

networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/30"
