version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    container_name: totem-container
    networks:
      app-network:
        ipv4_address: 192.168.10.2

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.10.0/24"
