version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8081"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    container_name: totem-container
    networks:
      - totem-network


networks:
  totem-network:
      external: true
