version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    container_name: totem-container
    networks:
      - totem-network
    network_mode: host


networks:
  totem-network:
      driver: bridge
