spring.application.name: totem
server:
  port: 8000

data:
  mongodb:
    database: totem
    uri: mongodb://172.18.0.1:27017/totem?authSource=admin

# application.properties
mqtt.broker.url: tcp://localhost:1883
mqtt.client.id: spring-mqtt-client
